version: '3'
services:
    mailcatcher:
        image: schickling/mailcatcher
        ports: [1025, 1080]

    db:
        image: mysql:5.7
        # permet de stocker l'ensemble du contenu du dossier /var/lib/mysql dans un disque persistant
        volumes:
        - ./var/docker/db:/var/lib/mysql
        # politique de redémarrage du conteneur en cas d'erreur fatale
        restart: always
        # valeurs des différents mots de passe et utilisateurs qui doivent exister sur cette base
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
        # command: --max-allowed-packet=67108864 --sql_mode="STRICT_ALL_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER"
        ports:
            - 8086:3306
   
    ##  Le système de fichiers Wordpress
  
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - "db:db"
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        volumes:
        - ./var/docker/php-ini/php.ini:/usr/local/etc/php/php.ini
        
        restart: always
        ports:
            - "8005:80"